import {
  Booking,
  Branch,
  DashboardStats,
  PortfolioItem,
  SalonService,
  StaffMember,
} from "./types";

export const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));

export let MOCK_BRANCHES: Branch[] = [
  {
    id: 1,
    name: "Éclat - Manhattan",
    address: "5th Avenue, NY 10010",
    city: "New York",
    phone: "212-555-0101",
    email: "manhattan@eclatsalonnyc.com",
    hours: "Mon-Sat: 9am-8pm, Sun: 10am-5pm",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bfcfaa6362f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Éclat - Brooklyn",
    address: "Bedford Ave, NY 11211",
    city: "New York",
    phone: "718-555-0102",
    email: "brooklyn@eclatsalonnyc.com",
    hours: "Mon-Sat: 10am-9pm, Sun: Closed",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export let MOCK_SERVICES: SalonService[] = [
  {
    id: 1,
    name: "Classic Haircut",
    category: "Hair",
    price: "85.00",
    duration: "45 mins",
    description: "Experience our premium Classic Haircut service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Balayage Color",
    category: "Hair",
    price: "150.00",
    duration: "120 mins",
    description: "Experience our premium Balayage Color service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1600948836101-f9ffda59d250?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Keratin Treatment",
    category: "Hair",
    price: "200.00",
    duration: "90 mins",
    description: "Experience our premium Keratin Treatment service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f10d5e43?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Radiant Glow Facial",
    category: "Beauty",
    price: "150.00",
    duration: "60 mins",
    description: "Experience our premium Radiant Glow Facial service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Anti-Aging Treatment",
    category: "Beauty",
    price: "180.00",
    duration: "75 mins",
    description: "Experience our premium Anti-Aging Treatment service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Microdermabrasion",
    category: "Beauty",
    price: "120.00",
    duration: "45 mins",
    description: "Experience our premium Microdermabrasion service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Ayurvedic Herbal Spa",
    category: "Herbal spa",
    price: "180.00",
    duration: "90 mins",
    description: "Experience our premium Ayurvedic Herbal Spa service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Hot Stone Therapy",
    category: "Herbal spa",
    price: "130.00",
    duration: "60 mins",
    description: "Experience our premium Hot Stone Therapy service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Aromatherapy Massage",
    category: "Herbal spa",
    price: "140.00",
    duration: "75 mins",
    description: "Experience our premium Aromatherapy Massage service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Deep Tissue Massage",
    category: "Massaging Therapy",
    price: "120.00",
    duration: "60 mins",
    description: "Experience our premium Deep Tissue Massage service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: "Swedish Massage",
    category: "Massaging Therapy",
    price: "100.00",
    duration: "60 mins",
    description: "Experience our premium Swedish Massage service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: "Reflexology",
    category: "Massaging Therapy",
    price: "90.00",
    duration: "45 mins",
    description: "Experience our premium Reflexology service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: "Luxury Mani-Pedi",
    category: "Manicure & Pedicure",
    price: "85.00",
    duration: "75 mins",
    description: "Experience our premium Luxury Mani-Pedi service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1519014816548-bf5fe059e98b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: "Classic Manicure",
    category: "Manicure & Pedicure",
    price: "35.00",
    duration: "30 mins",
    description: "Experience our premium Classic Manicure service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: "Spa Pedicure",
    category: "Manicure & Pedicure",
    price: "55.00",
    duration: "45 mins",
    description: "Experience our premium Spa Pedicure service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1519014816548-bf5fe059e98b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 16,
    name: "Premium Gel Extensions",
    category: "Gel Nails",
    price: "110.00",
    duration: "90 mins",
    description: "Experience our premium Premium Gel Extensions service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 17,
    name: "Gel Polish Change",
    category: "Gel Nails",
    price: "45.00",
    duration: "30 mins",
    description: "Experience our premium Gel Polish Change service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1519014816548-bf5fe059e98b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 18,
    name: "Nail Art Design",
    category: "Gel Nails",
    price: "30.00",
    duration: "30 mins",
    description: "Experience our premium Nail Art Design service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 19,
    name: "Bridal Makeup Package",
    category: "Makeup",
    price: "350.00",
    duration: "180 mins",
    description: "Experience our premium Bridal Makeup Package service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 20,
    name: "Evening Party Makeup",
    category: "Makeup",
    price: "120.00",
    duration: "60 mins",
    description: "Experience our premium Evening Party Makeup service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 21,
    name: "Natural Day Look",
    category: "Makeup",
    price: "85.00",
    duration: "45 mins",
    description: "Experience our premium Natural Day Look service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 22,
    name: "Full Body Waxing",
    category: "Waxing",
    price: "95.00",
    duration: "60 mins",
    description: "Experience our premium Full Body Waxing service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1558066597-9e46a5b4c107?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 23,
    name: "Brazilian Wax",
    category: "Waxing",
    price: "60.00",
    duration: "45 mins",
    description: "Experience our premium Brazilian Wax service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 24,
    name: "Half Leg Waxing",
    category: "Waxing",
    price: "40.00",
    duration: "30 mins",
    description: "Experience our premium Half Leg Waxing service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1558066597-9e46a5b4c107?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 25,
    name: "Eyebrow Threading",
    category: "Threading",
    price: "25.00",
    duration: "15 mins",
    description: "Experience our premium Eyebrow Threading service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1555820597-40b490d18833?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 26,
    name: "Upper Lip Threading",
    category: "Threading",
    price: "15.00",
    duration: "10 mins",
    description: "Experience our premium Upper Lip Threading service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 27,
    name: "Full Face Threading",
    category: "Threading",
    price: "50.00",
    duration: "30 mins",
    description: "Experience our premium Full Face Threading service.",
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1555820597-40b490d18833?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export let MOCK_STAFF: StaffMember[] = [
  {
    id: 1,
    name: "Emma Stone",
    role: "Senior Stylist",
    branchId: 1,
    branchName: "Éclat - Manhattan",
    phone: "212-555-0201",
    email: "emma@eclatsalonnyc.com",
    rating: 4.9,
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Michael B.",
    role: "Color Specialist",
    branchId: 2,
    branchName: "Éclat - Brooklyn",
    phone: "718-555-0202",
    email: "michael@eclatsalonnyc.com",
    rating: 4.8,
    status: "ACTIVE",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export let MOCK_PORTFOLIO: PortfolioItem[] = [
  {
    id: 1,
    title: "Summer Balayage",
    category: "Hair Color",
    description: "Vibrant summer tones for a fresh look.",
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Modern Bob",
    category: "Haircut",
    description: "Chic and sharp bob cut.",
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f10d5e43?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export let MOCK_BOOKINGS: Booking[] = [
  {
    id: 1,
    branchId: 1,
    branchName: "Éclat - Manhattan",
    services: ["Classic Haircut", "Luxury Manicure"],
    date: "2026-07-15",
    time: "14:00",
    customerName: "Alice Smith",
    phone: "555-0301",
    email: "alice@example.com",
    status: "CONFIRMED",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    branchId: 1,
    branchName: "Éclat - Manhattan",
    services: ["Balayage"],
    date: "2026-07-16",
    time: "10:00",
    customerName: "Bob Johnson",
    phone: "555-0302",
    email: "bob@example.com",
    status: "PENDING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export let MOCK_DASHBOARD_STATS: DashboardStats = {
  totalBookings: 156,
  pendingBookings: 12,
  confirmedBookings: 45,
  completedBookings: 89,
  cancelledBookings: 10,
  totalServices: MOCK_SERVICES.length,
  activeStaff: MOCK_STAFF.length,
  totalBranches: MOCK_BRANCHES.length,
  bookingsByStatus: {
    PENDING: 12,
    CONFIRMED: 45,
    COMPLETED: 89,
    CANCELLED: 10,
  },
};
